### ISSUE TITLE
rust cookbook doc

### ISSUE THREAD

**Issue by ghudgins** [flox/floxdocs#3]
### Notes

* IA proposal from @zmitchell  - Cookbooks --> Languages --> Python
* @zmitchell ideas for content: Activate a virtual env with Flox, where to put that, etc. Copy/paste auto init thing in there. Explain what it does. Minimal amount of understanding and off to the races.

Sections brainstorm
* How do I incrementally migrate to Flox? 1/ use flox to get lang tools....etc when do you use flox-provided packages vs. rust ecosystem
* set up virtual env
* add Flox to existing rust project
* what if Flox doesn't have the package I want
* what if it doesn't find my rust packages (debugging thing)

**Comment by zmitchell** [comment]
This is already completed
