### ISSUE TITLE
Document manifest builds for a few languages

### ISSUE THREAD

**Issue by mkenigs** [flox/floxdocs#81]
Document manifest builds for:
- [ ] Node
- [ ] Python
- [ ] Go
- [ ] Make

TODO: I'm unsure of exactly what details need to be documented

**Comment by mkenigs** [comment]
There's some existing documentation at https://www.notion.so/floxdev/Flox-Builds-13e744c8e316800dbe18f5ffbf8c2fa0

**Comment by garbas** [comment]
We should also update the example environments for those languages

**Comment by zmitchell** [comment]
We decided to keep a long-running branch for `build` docs so that we can use the docs during interviews, but not have them otherwise publicly visible.

**Comment by zmitchell** [comment]
https://github.com/flox/floxdocs/pull/92
